### ISSUE TITLE
[].map vs [].forEach

### ISSUE THREAD

**Issue by Phizzard** [rotunstall/NBA-League-Pass#2]
https://github.com/rotunstall/NBA-League-Pass/blob/84cd1a491ee71a66a3db25c66171f3a0aceeb5f9/js/scripts.js#L17-L22

The reason why `teamsData` is an array of undefined values is because you are using prototype.map without returning anything, and instead attempting to push into the array.

For the above code to work you would need something like

```
const newArray = oldArray.map((item) => {
  // ...some stuff
  return item; 
  // This doesn't have to be [item], it's whatever you want to be added into the array at each index
}); 
```

This would have the equivalent results as

```
let newArray = [];
oldArray.forEach((item) => {
  // ...some stuff
  newArray.push(item);
});
```

The key difference between forEach and map is that forEach will not return anything, whereas .map will return a new array based on the provided function that will run on every entry in the array it's looping through.

Should just need a one line change to get it working :)

**Comment by rotunstall** [comment]
I get what I need from the console.log that is inside getTeamsData function, but how do I assign it to the variable outside the function? 


```
let teamsData = [];

document.addEventListener("DOMContentLoaded", function getTeamsData() {
	axios({
		method: "get",
		url:
			"https://www.thesportsdb.com/api/v1/json/1/lookup_all_teams.php?id=4387"
	})
		.then((res) => {
			teamsData = [...res.data.teams].map((item) => {
				buildConferences(item);
				buildDivisions(item);
				// teamsData.push(item);
				return item;
			});
			console.log(teamsData);
		})
		.catch((err) => console.error(err));
});
```

**Comment by rotunstall** [comment]
This is the closest I have been able to get what I need. The new array of objects is really not an array of objects that you can access.

```
let teamsData = [];

document.addEventListener("DOMContentLoaded", function getTeamsData() {
	axios({
		method: "get",
		url:
			"https://www.thesportsdb.com/api/v1/json/1/lookup_all_teams.php?id=4387"
	})
		.then((res) => {
			[...res.data.teams].map((item) => {
				buildConferences(item);
				buildDivisions(item);
				return teamsData.push(item);
			});
			console.log(teamsData);
		})
		.catch((err) => console.error(err));
});
```

**Comment by Phizzard** [comment]
What you had in the first comment will update `teamsData`, just only once the request has been completed and the block of code in the `.then` has been executed.

the console log further down the js file will still be undefined as it's in the main body of the file and is likely firing before the promise is completed.

Promises are asynchronous, this means that the rest of the code in the file can continue going while the promise is being made.
```
document.addEventListener("DOMContentLoaded", function getTeamsData() {
  axios({
    method: "get",
    url: "https://www.thesportsdb.com/api/v1/json/1/lookup_all_teams.php?id=4387",
  })
    .then((res) => {
      teamsData = [...res.data.teams].map((item) => {
        buildConferences(item);
        buildDivisions(item);
        return item;
      });
    })
    .catch((err) => console.error(err));
});
```

With the above, I'm able to select teams from the list and the page data updates with the team information.

If you want to render out all the list of teams based on the results of getTeamsData(), it will have to be done inside the .then() block after the loop.
